liip_imagine:
    loaders:
        default:
            filesystem:
                locator: filesystem_insecure
                data_root: "%kernel.root_dir%/../var"
    driver: "gd"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../public"

    # Filtrai
    filter_sets:
        #resize_standart
        resize_standard:
            quality: 80
            filters:
                relative_resize:
                    widen: 800
                    allow_upscale: true 