sensio_framework_extra:
    router:     { annotations: false }
    request:    { converters: true, auto_convert: false }
    view:       { annotations: false }
    cache:      { annotations: false }
    security:   { annotations: false }